### ISSUE TITLE
rcspline.plot

### ISSUE THREAD

**Issue by CorradoLanera** [CorradoLanera/SuDACDa#2]
The output print is very ugly. options `noprint` doesn't work

**Comment by CorradoLanera** [comment]
Reported to harrelfe/Hmisc#79

**Comment by couthcommander** [comment]
I saw the Hmisc report - `noprint` doesn't work quite like you'd expect.  If your goal is to hide all output, you may try `invisible(capture.output(rcspline.plot(...)))`.

**Comment by CorradoLanera** [comment]
It works, thank you! (I really do not understand the aims of this options...)
